require("./schematize/String");
require("./schematize/Number");
typeof BigInt === "function" && require("./schematize/BigInt");
require("./schematize/Boolean");
require("./schematize/Symbol");
require("./schematize/Object");
require("./schematize/Array");
require("./schematize/Date");
require("./schematize/RegExp");
require("./schematize/Map");
require("./schematize/Set");
require("./schematize/Buffer");
require("./schematize/TypedArray");
typeof URL === "function" && require("./schematize/URL");
require("./schematize/Error");
require("./schematize/others");
require("./schematize/common");

require("./match/String");
require("./match/Number");
typeof BigInt === "function" && require("./match/BigInt");
require("./match/Boolean");
require("./match/Symbol");
require("./match/Object");
require("./match/Array");
require("./match/Buffer");
require("./match/TypedArray");
require("./match/common");
